spring.application.name=parcelsafe-api

server.port=3000

# MongoDB Configuration
spring.mongodb.uri=mongodb://admin:admin123@localhost:27017/parcel_tracker?authSource=admin&authMechanism=SCRAM-SHA-256

# Set a development username and password
spring.security.user.name=admin
spring.security.user.password=password123
