spring.application.name=parcelsafe-api

server.port=3000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://admin:admin123@mongodb:27017/?authSource=admin
spring.data.mongodb.database=parcelsafe

# Set a development username and password
spring.security.user.name=admin
spring.security.user.password=password123
