; ----------------------------------------------------
; GLOBAL SETTINGS (Shared across all target hardware)
; ----------------------------------------------------
[env]
monitor_speed = 115200
build_flags = 
    -I inc              ; Makes PlatformIO globally look into your 'inc' folder
    -I target
    -Wl,-u,_printf_float
; ----------------------------------------------------
; TARGET 1: Arduino Uno R4 WiFi (Renesas Core)
; ----------------------------------------------------
[env:arduino_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
lib_deps =
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BMP280 Library @ ^2.6.8

build_flags = 
    ${env.build_flags}
    -D TARGET_ARDUINO

; This filter includes your main app, and strictly ONLY your Arduino hardware files 👇
build_src_filter = 
    +<../src/main.cpp>
    +<../target/arduino/>

; Instruct PlatformIO to inject the python macro layer right here! 👇
extra_scripts = 
    pre:load_config.py

; ----------------------------------------------------
; TARGET 2: STM32 Board (e.g., STM32F4 Discovery or BluePill)
; ----------------------------------------------------
[env:stm32_target]
platform = stm32
board = genericSTM32F407VGT6 ; Change this to your exact STM32 board ID
framework = stm32cube        ; Pure STM32 HAL framework (no Arduino magic!)

build_flags = 
    ${env.build_flags}
    -D TARGET_STM32

; This filter includes your main app, and strictly ONLY your STM32 hardware files 👇
build_src_filter = 
    +<../src/main.cpp>
    +<../target/stm32/>